{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "230efd3a-4529-487e-89e5-c6a6e1c878b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1. Uji reverse_per_kata\n",
      "UKA ATNIC UMAK\n",
      "\n",
      "2. Uji urutkan_kalimat\n",
      "PYTHON HARI BELAJAR SEDANG INI\n",
      "\n",
      "3. Uji ganti_vokal (opsi 1)\n",
      "Ak|_| C1nt4 K4m|_|\n",
      "\n",
      "4. Uji ganti_vokal (opsi 2)\n",
      "4ku Cinta Kamu\n"
     ]
    }
   ],
   "source": [
    "#=============================\n",
    "# Fungsi: reverse_per_kata\n",
    "# Tujuan:\n",
    "#   Membalik huruf-huruf pada setiap kata dalam kalimat\n",
    "#   tanpa mengubah urutan kata-katanya.\n",
    "# Cara kerja:\n",
    "#   - Split kalimat menjadi list kata\n",
    "#   - Tiap kata dibalik (menggunakan slicing)\n",
    "#   - Hasil digabungkan kembali menjadi satu string\n",
    "# ================================\n",
    "def reverse_per_kata(kalimat):\n",
    "    kata_list = kalimat.split()\n",
    "    hasil = [kata[::-1] for kata in kata_list]\n",
    "    return ' '.join(hasil)\n",
    "\n",
    "# ================================\n",
    "# Fungsi: urutkan_kalimat\n",
    "# Tujuan:\n",
    "#   Mengubah urutan kata-kata dalam kalimat sesuai dengan\n",
    "#   urutan indeks yang diberikan (berbasis 1, bukan 0).\n",
    "# Cara kerja:\n",
    "#   - Split kalimat menjadi list kata\n",
    "#   - Buat list kosong sesuai panjang urutan\n",
    "#   - Tempatkan kata pada posisi baru sesuai indeks\n",
    "#   - Gabungkan hasilnya menjadi string\n",
    "# Catatan:\n",
    "#   Jika jumlah indeks tidak sama dengan jumlah kata,\n",
    "#   fungsi akan mengembalikan pesan error.\n",
    "# ================================\n",
    "def urutkan_kalimat(kalimat, urutan):\n",
    "    kata_list = kalimat.split()\n",
    "    if len(kata_list) != len(urutan):\n",
    "        return \"Jumlah kata dan indeks urutan tidak cocok!\"\n",
    "    \n",
    "    hasil = [''] * len(urutan)\n",
    "    for i in range(len(urutan)):\n",
    "        posisi_baru = urutan[i] - 1  # sesuaikan karena list di Python 0-indeks\n",
    "        hasil[i] = kata_list[posisi_baru]\n",
    "    \n",
    "    return ' '.join(hasil)\n",
    "\n",
    "# ================================\n",
    "# Fungsi: ganti_vokal\n",
    "# Tujuan:\n",
    "#   Mengganti huruf vokal pada kalimat dengan simbol tertentu.\n",
    "#   Opsi:\n",
    "#     1 -> hanya huruf vokal kecil yang diganti\n",
    "#     2 -> hanya huruf vokal kapital yang diganti\n",
    "# Cara kerja:\n",
    "#   - Gunakan dictionary pemetaan vokal ke simbol\n",
    "#   - Loop setiap huruf di kalimat\n",
    "#   - Ganti sesuai opsi\n",
    "#   - Gabungkan semua huruf ke hasil string\n",
    "# ================================\n",
    "def ganti_vokal(kalimat, opsi):\n",
    "    vokal_map = {\n",
    "        'a': '4', 'i': '1', 'u': '|_|', 'e': '3', 'o': '0',\n",
    "        'A': '4', 'I': '1', 'U': '|_|', 'E': '3', 'O': '0'\n",
    "    }\n",
    "    \n",
    "    hasil = ''\n",
    "    for huruf in kalimat:\n",
    "        if opsi == 1 and huruf in 'aiueo':\n",
    "            hasil += vokal_map[huruf]\n",
    "        elif opsi == 2 and huruf in 'AIUEO':\n",
    "            hasil += vokal_map[huruf]\n",
    "        else:\n",
    "            hasil += huruf\n",
    "    return hasil\n",
    "\n",
    "# ================================\n",
    "# Bagian Pengujian Fungsi\n",
    "# ================================\n",
    "\n",
    "print(\"1. Uji reverse_per_kata\")\n",
    "print(reverse_per_kata(\"AKU CINTA KAMU\"))\n",
    "# Output: \"UKA ATNIC UMAK\"\n",
    "\n",
    "print(\"\\n2. Uji urutkan_kalimat\")\n",
    "print(urutkan_kalimat(\"HARI INI SEDANG BELAJAR PYTHON\", [5, 1, 4, 3, 2]))\n",
    "# Output: \"PYTHON HARI BELAJAR SEDANG INI\"\n",
    "\n",
    "print(\"\\n3. Uji ganti_vokal (opsi 1)\")\n",
    "print(ganti_vokal(\"Aku Cinta Kamu\", 1))\n",
    "# Output: \"Ak|_| C1nt4 K4m|_|\"\n",
    "\n",
    "print(\"\\n4. Uji ganti_vokal (opsi 2)\")\n",
    "print(ganti_vokal(\"Aku Cinta Kamu\", 2))\n",
    "# Output: \"4ku Cinta K4mu\"\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
